name: CD
on: [push, pull_request]
jobs:
  linux:
    name: linux
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xsltproc
      run: |
        sudo apt-get update && sudo apt-get install xsltproc -y

    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so

    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2 
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so
    - name: Change Artifact Name
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.so
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.so
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.so
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP-generic64.so
          mv bin/generic64/libXKCP.so.headers bin/artifacts/libXKCP-linux.so.headers
          ls bin/artifacts
    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-linux
        path: |
          bin/artifacts/*.so
          bin/artifacts/libXKCP-linux.so.headers
  osx:
    name: osx
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install xsltproc
      run: |
        brew install libxslt
    - name: Build Generic64
      run: |
        CFLAGS="-O3 -g0 -march=ivybridge -mtune=native" ASMFLAGS="-march=ivybridge -mtune=native" make generic64/libXKCP.so
    - name: Build SSSE3
      run: |
        CFLAGS="-O3 -g0 -march=corei7 -mtune=native" ASMFLAGS="-march=corei7 -mtune=native" make SSSE3/libXKCP.so
    - name: Build AVX2 
      run: |
        CFLAGS="-O3 -g0 -march=skylake -mtune=native" ASMFLAGS="-march=skylake -mtune=native" make AVX2/libXKCP.so
    - name: Build AVX512
      run: |
        CFLAGS="-O3 -g0 -march=skylake-avx512 -mtune=native" ASMFLAGS="-march=skylake-avx512 -mtune=native" make AVX512/libXKCP.so

    - name: Change Artifact Name
      run: |
          mkdir bin/artifacts
          mv bin/AVX2/libXKCP.so bin/artifacts/libXKCP-AVX2.dylib
          mv bin/AVX512/libXKCP.so bin/artifacts/libXKCP-AVX512.dylib
          mv bin/SSSE3/libXKCP.so bin/artifacts/libXKCP-SSSE3.dylib
          mv bin/generic64/libXKCP.so bin/artifacts/libXKCP-generic64.dylib
          mv bin/generic64/libXKCP.so.headers bin/artifacts/libXKCP-osx.so.headers
          ls bin/artifacts
    - name: Upload osx Artifact
      uses: actions/upload-artifact@v2
      with:
        name: XKCP-osx
        path: |
          bin/artifacts/*.dylib
          bin/artifacts/libXKCP-osx.so.headers
  create-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [linux,osx]
    steps:
      - name: Download XKCP linux
        uses: actions/download-artifact@v2
        with:
          name: XKCP-linux
          path: linux

      - name: Download XKCP osx
        uses: actions/download-artifact@v2
        with:
          name: XKCP-osx
          path: osx        

      - name: Zip file
        run: |
          mkdir artifacts/
          tar czf artifacts/XKCP-linux.tar.gz -C linux/ $(find linux -type f -name "*.so" -exec basename {} \;) libXKCP-linux.so.headers/
          tar czf artifacts/XKCP-osx.tar.gz -C osx/ $(find osx -type f -name "*.dylib" -exec basename {} \;) libXKCP-osx.so.headers/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: XKCP
          files: |
            artifacts/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}