on:
  schedule:
    - cron:  '0 7 * * 1,4'
  workflow_dispatch: 
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync main with upstream latest
    steps:
    - name: Checkout stirling-labs branch
      uses: actions/checkout@v2
      with:
        ref: stirling-labs

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.3
      with:
        upstream_repository: XKCP/XKCP
        upstream_branch: master
        target_branch: stirling-labs
        git_pull_args: '--allow-unrelated-histories'                
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create new commit
      if: steps.sync.outputs.has_new_commits
      run: |
        git config --global user.email "tyler.young@stirlinglabs.com"
        git config --global user.name "TYoungSL"
        echo 'New changes Upstream XKCP' > xkcp.md
        git add -A
        git commit -m "XKCP/XKCP main branch has changes"        
    - name: Create Pull Request
      if: steps.sync.outputs.has_new_commits
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ''
        branch: check-xkcp-upsteram
        body: |
          - Please check changes upstream XKCP master branch.
        labels: |
          automated-pr